# Generated by Django 3.2.8 on 2022-03-14 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0005_auto_20220314_1845'),
    ]

    operations = [
    ]
