# Generated by Django 3.2.8 on 2022-03-14 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0006_remove_top10_university'),
    ]

    operations = [
    ]
